name: go_router_example_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.0.1
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  get_it: ^7.2.0
  equatable: ^2.0.5
  health: ^4.4.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
